name: Deploy to Streamlit Community Cloud

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test app
      run: |
        streamlit run app.py --server.headless true --server.port 8501 --server.address 0.0.0.0 &
        sleep 10
        curl -f http://localhost:8501/_stcore/health || exit 1
